project/blog/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import views as auth_views
from . import views
from .views import ListingUpdate, ListingDelete

import notifications

# Each url pattern is tied to a view.
# If you check views.py, you'll notice that we are defining "base".
urlpatterns = [
	url(r'^$', views.base, name='base'),
	url(r'^about$', views.about, name='about'),
	url(r'^register$', views.register, name='register'),
    url(r'^listing_list$', views.listing_list, name='listing_list'),

    # Using Django's built-in login view.
	url(r'^login$', auth_views.login, {'template_name': 'blog/login.html'}, name='login'),
    
	# Here we pass Django's built-in logout view, then we redirect back to "base" view.
	url(r'^logout$', auth_views.logout, 
		{
			"next_page": reverse_lazy('base')
		}, name='logout'),

	# This is for viewing blog listings individually.
	url(r'^listing/(?P<listing_id>[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})$', views.listing_detail, name='listing_detail'),
	url(r'^listing/new$', views.listing_new, name='listing_new'),
	url(r'^listing/delete/(?P<listing_id>[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})$', ListingDelete.as_view(), name='listing_delete'),
	url(r'^listing/update/(?P<listing_id>[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})$', ListingUpdate.as_view(), name='listing_update'),

	url(r'^search$', views.search, name='search'),

	# The following url patters are for the notifications feature.
	url(r'^inbox/notifications/', include(notifications.urls), name='notifications'),
	url(r'^inbox/notifications/mark-all-as-read$', views.mark_all_as_read, name='mark_all_as_read'),
	url(r'^get-interested-users$', views.get_interested_users, name='get_interested_users'),
	url(r'^send-notification$', views.send_notification, name='send_notification'),
	
	# Below is for the url of the pictures uploaded by users

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('blog.urls')),
]

project/blog/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse_lazy, reverse
import uuid

# Create your models here.

# This models the Listing object that we will use to create listings.
class Listing(models.Model):
	# Each model has its own attributes.
	key = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	author = models.ForeignKey('auth.User')
	price = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
	title = models.CharField(max_length=200)
	text = models.TextField()
	created_date = models.DateTimeField(default=timezone.now)
	published_date = models.DateTimeField(blank=True, null=True)

	def publish(self):
		self.published_date = timezone.now()
		self.save()

	def get_absolute_url(self):
		return reverse('blog.views.listing_detail', args=[str(self.key)])

	def __str__(self):
		return self.title

# A Many to one model for Listing. Represents pictures in a Listing.
class ListingPicture(models.Model):
	# Automatically uploads to the media/ directory.
	picture = models.ImageField(upload_to='', blank=True)
	picture_id = models.ForeignKey(Listing)

project/blog/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth import authenticate, login
from .models import Listing, ListingPicture

from django.contrib.auth.models import User

from decimal import *

# This is a form which defines the fields the user sees when registering/logging in. 
class UserForm(forms.Form):
	username = forms.CharField(label='Username')
	password = forms.CharField(widget=forms.PasswordInput())

	def clean_username(self):
		username = self.cleaned_data['username']
		if User.objects.filter(username=username).exists():
			raise forms.ValidationError("That username is already taken")
		return username

class ListingForm(forms.ModelForm):
	class Meta:
		model = Listing
		fields = ('title', 'price', 'text', )

	def clean_price(self):
		price = self.cleaned_data['price']
		if price < Decimal('0.00'):
			raise forms.ValidationError("Price cannot be negative")
		return price

class ListingPictureForm(forms.ModelForm):
	class Meta:
		model = ListingPicture
		fields = ('picture', )

		

project/blog/views.py
import os
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.core.urlresolvers import reverse_lazy, reverse
from django.core.exceptions import ValidationError
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.utils import timezone

from .models import Listing, ListingPicture
from .forms import UserForm, ListingForm, ListingPictureForm
from django.forms import modelformset_factory

from django.forms.models import model_to_dict

from django.views.generic import View
from django.views.generic.edit import UpdateView, DeleteView
from django.views.generic.detail import SingleObjectMixin

from django.core.files.uploadedfile import InMemoryUploadedFile

from django.db.models import Q

from notifications import notify

# This function takes a formset, cleans it, enumerates it, and saves the corresponding object to the database. 
# This function is not a view; just providing a service.
def savePictureFormToDB(pictureFormSet, listing):
	# Get data from the form
	cleaned_data = pictureFormSet.cleaned_data
	print("cleaned_data:", cleaned_data)

	# For each picture the user uploads, create a corresponding ListingPicture object
	for index, pic in enumerate(pictureFormSet):
		# If the form is empty, break out of this loop.
		if cleaned_data[index] == {}:
			break

		clean_pic = cleaned_data[index]['picture']
		clean_id = cleaned_data[index]['id']

		# If the user checked the "Clear" check-box, delete the image.
		if clean_pic == False:
			os.remove(clean_id.picture.path)
			clean_id.delete()
		
		# This checks if the image is the one that was uploaded (instance of InMemoryUploadedFile). 
		# If we do not have this check, we will create duplicates,
		# since the code will add every image from the form (including existing ones).
		# Images that have already been uploaded are instances of ImageFieldFile.
		elif not isinstance(clean_pic, InMemoryUploadedFile):
			continue

		# If the image is an instance of InMemoryUploadedFile, save to DB.
		else:
			picture = ListingPicture.objects.create(picture=clean_pic, picture_id=listing)
			picture.save()
	return

# Defining a generic editing views for handling when the user wants to edit/update their listing.
class ListingUpdate(UpdateView):
	model = Listing
	template_name = 'blog/listing_update.html'
	pk_url_kwarg = 'listing_id'
	fields = ['title', 'price', 'text']

	# Here we are instantiating a formset with ListingPictureForm.
	ListingPictureFormSet = modelformset_factory(ListingPicture, form=ListingPictureForm, extra=5, max_num=5)
	pictureFormSet = None

	# Overriding UpdateView's post() method in order to provide our own implementation.
	def post(self, request, listing_id):
		# Initializing formset with existing pictures from the listing (queryset).
		pictureFormSet = self.ListingPictureFormSet(request.POST, request.FILES, queryset=ListingPicture.objects.filter(picture_id=listing_id))

		listingForm = ListingForm(request.POST)

		# Set the object instance in case user cancels their delete request.
		# Must be called self.object since we are overriding the UpdateView's self.object.
		self.object = get_object_or_404(Listing, pk=listing_id)
		if request.user == self.object.author:

			# Verify if the listing form is valid.
			# If not, call the super class's form_invalid() method which automatically handles invalid forms.
			if listingForm.is_valid():
				pass
				#print(listingForm.cleaned_data)
				#price = listingForm.clean_price()
			else:
				return super(UpdateView, self).form_invalid(listingForm)

			# Save updated picture form to database if there's been a change
			if pictureFormSet.is_valid() and pictureFormSet.has_changed():
				print("valid and has changed")
				savePictureFormToDB(pictureFormSet, self.object)
			else:
				print("errors:", pictureFormSet.errors)
			return super(ListingUpdate, self).post(request, listing_id)
		else:
			# Return to main page if user tries perform an unauthorized action.
			return HttpResponseRedirect("/")

	# Overriding UpdateView's get_context_data() method in order to include the formset in the template.
	def get_context_data(self, **kwargs):
		# Get context object from UpdateView.
		context = super(ListingUpdate, self).get_context_data(**kwargs)
		try:
			# Build a picture formset based on the listing the user is editing. 
			pictureFormSet = self.ListingPictureFormSet(queryset=ListingPicture.objects.filter(picture_id=context['listing'].key))
			# Pass it to the context object so it's accessible to the template.
			# This is equivalent to render(request, <template path>, {'pictures': pictureFormSet})
			context['pictures'] = pictureFormSet
		except Exception as e:
			context['pictures'] = None
		return context

# Defining a generic delete views for handling when the user wants to delete their listing.
class ListingDelete(DeleteView):
	model = Listing
	pk_url_kwarg = 'listing_id'
	success_url = reverse_lazy('listing_list')

	# Overriding DeleteView's post() in order to provide our own implementation.
	def post(self, request, listing_id):
		# Set the object instance in case user cancels their delete request.
		# Must be called self.object since we are overriding the DeleteView's self.object.
		self.object = get_object_or_404(Listing, pk=listing_id)
		if request.user == self.object.author:
			# "Cancel" refers to the tag <input name="Cancel" ...> from the template listing_confirm_delete.html
			if "Cancel" in request.POST:
				url = self.get_success_url()
				return HttpResponseRedirect(url)
			else:
				return super(ListingDelete, self).post(request, listing_id)
		else:
			# Return to main page if user tries perform an unauthorized action.
			return HttpResponseRedirect("/")

# Defining the base view here. Basic homepage.
def base(request):
	# We return a rendered index.html
	return render(request, 'blog/index.html', {})

# Define a basic about page.
def about(request):
	return render(request, 'blog/about.html', {})

# This is for registering a new account on the site.
def register(request):
	if request.method == "POST":
		form = UserForm(request.POST)
		if form.is_valid():
			username, password = form.clean_username(), form.cleaned_data['password']
			user = User.objects.create_user(username=username, password=password)
			user.is_active = True
			user.save()
			new_user = authenticate(username=username, password=password)
			login(request, new_user)
			return HttpResponseRedirect("/listing_list")
	else:
		form = UserForm()

	return render(request, 'blog/register.html', {'form': form})

# When the user clicks the "Browse" button in the navbar.
def listing_list(request):
	listings = Listing.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	return render(request, 'blog/listing_list.html', {'listings': listings})

# For viewing a listing individually. We load the primary key of the listing from the database.
# Refer to the <a> tag inside listing_list.html 
def listing_detail(request, listing_id):
	listing = get_object_or_404(Listing, pk=listing_id)
	pictures = ListingPicture.objects.filter(picture_id=listing_id)
	return render(request, 'blog/listing_detail.html', {'listing': listing, 'pictures': pictures})

# For creating a new listing.
def listing_new(request):
	ListingPictureFormSet = modelformset_factory(ListingPicture, form=ListingPictureForm, extra=5, max_num=5)

	if request.method == "POST":
		form = ListingForm(request.POST)
		pictureFormSet = ListingPictureFormSet(request.POST, request.FILES, queryset=ListingPicture.objects.none())

		if form.is_valid():
			title, text, price = form.cleaned_data['title'], form.cleaned_data['text'], form.clean_price()
			listing = Listing.objects.create(author=request.user, title=title, text=text, price=price)
			listing.publish()

			if pictureFormSet.is_valid():
				savePictureFormToDB(pictureFormSet, listing)

			return HttpResponseRedirect("/listing_list")
	else:
		form = ListingForm()
		pictureFormSet = ListingPictureFormSet(queryset=ListingPicture.objects.none())

	return render(request, 'blog/listing_new.html', {'form': form, 'pictureFormSet': pictureFormSet})

# This view is for handling the search queries.
# Utilizing Q objects provided by Django:
# https://docs.djangoproject.com/en/1.8/topics/db/queries/#complex-lookups-with-q-objects
def search(request):
	if request.method == "GET":	
		query = request.GET.get('search_box', None)
		results = Listing.objects.filter(
				Q(title__contains=query) | Q(text__contains=query),
				published_date__lte=timezone.now()
			).order_by('published_date')
		
		# Return results to already created listing_list template; no need to have an extra template.
		return render(request, 'blog/listing_list.html', {'listings': results})

# Marks all user's notifications as read; redirects to current page.
def mark_all_as_read(request):
	request.user.notifications.mark_all_as_read()

	return HttpResponseRedirect(request.META['HTTP_REFERER'])

# AJAX View to return the list of users who are interested in the listing.
def get_interested_users(request):
	# Make sure the request is AJAX and POST
	if request.is_ajax() and request.method == 'POST':
		if 'listingID' in request.POST:
			try:
				unread_list = []

				for n in request.user.notifications.unread().filter(action_object_object_id=request.POST['listingID']):
					struct = model_to_dict(n)
					if n.actor:
						struct['actor'] = str(n.actor)
					
					struct['description'] = "User " + struct['actor'] + " is interested"

					unread_list.append(struct)

				data = {
					'response': 'success',
					'unread_list':unread_list
				}

				return JsonResponse(data)
			except Exception as e:
				print(e)
				data = {
					'response': 'fail',
				}
				return JsonResponse(data)
	
	return JsonResponse({'response': 'fail'})



# AJAX View to send a notification to the author of the listing when a user click the "I'm Interested" button.

project/blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}

<div class="page-header">
    <h1>Team Int-erpreters</h1>
</div>
<h3>Members:</h3>
<ul>
    <li>Suraj Bennur</li>
    <li>Christopher Tarazi</li>
    <li>Doris Leong</li>
    <li>Krutik Amin</li>
    <li>Vu Mai</li>
    <li>Elias Raegany</li>
    <li>Alan Baker</li>
</ul>
{% endblock %}

project/blog/templates/blog/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Project: Market362</title>
    {% load staticfiles %}
    {% load notifications_tags %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'blog/content/site.css' %}" />
	<link rel="icon" href="{% static 'blog/img/favicon.ico' %}" />
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
    <script src="{% static 'blog/scripts/modernizr-2.6.2.js' %}"></script>
</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top container-fluid">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="{% url 'base' %}" class="navbar-brand">Market362</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="navbar-text"><a href="{% url 'listing_list' %}">Browse</a></li>
				</ul>
                <form class="navbar-form navbar-left" role="search" type="get" action="{% url 'search' %}">
                    <div class="form-group">
                        <input id="search_box" type="text" class="form-control" name="search_box"  placeholder="Search Listings" >
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
				{% include 'blog/loginpartial.html' %}
			</div>
		</div>
	</nav>

    <div class="container body-content">
		<!-- Content goes here -->
        {% block content %}
        {% endblock %}

        <footer class="footer">
            <p>&copy; 2015 - Team Int-erpreters</p>
        </footer>
    </div>

    <script src="{% static 'blog/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'blog/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'blog/scripts/respond.js' %}"></script>
    <script src="{% static 'blog/scripts/image-hover-selector.js' %}"></script>
    
    <!-- Include the following notification scripts if a user is logged in -->
    {% if request.user.is_authenticated %}
    <script src="{% static 'notifications/notify.js' %}"></script>
    {% register_notify_callbacks callbacks='fill_notification_badge' %}
    <script type="text/javascript">
        // Notification menu script for adding/removing notifications.

        // <seen> holds the slug of every notification we've received.
        // <urlDelete> is a hashmap that maps a slug -> api url to mark notification as read.  
        var seen = [];
        var urlDelete = {};
        var timer;

        function removeNotification(elem) {
            // Get slug key from the element's id
            var key = $(elem)[0].id.replace("notification", '');
            elem.off();
            elem.remove();
            // console.log("element removed at urlDelete[" + key + "] = " + urlDelete[key]);

            $.ajax({
                url: urlDelete[key],
                type: 'get', 
                success: function(data) {
                    // console.log("marked as read");
                },
                failure: function(data) { 
                    // console.log('failure to mark as read');
                }
            }); 

            // Update data; from notifiy.js
            fetch_api_data();
        }

        function insertNotifications(data) {
            for (var i = 0; i < data.unread_list.length; i++) {
                var slug = data.unread_list[i].slug
                urlDelete[slug] = data.unread_list[i].url_delete;
                if (seen.indexOf(slug) === -1) {
                    
                    // Append to the list a "<a><li></li></a>"
                    var tagsAppend = "<li id='notification" +
                        slug + "' > " + data.unread_list[i].description + 
                        "<label class='label label-primary'>" + 
                        "<span class='glyphicon glyphicon-ok' aria-hidden='true'></span></label> </li>"

                    var elem = $('#live-notify-list').append(tagsAppend).find('#notification' + slug);
                    elem.wrap("<a href='#'></a>");

                    $('#notification' + slug).append("<br><p role='separator' class='divider'></p>");

                    // console.log("inserted element with slug " + slug);

                    seen.push(slug);                  
                }
                else {
                   var updateElem = $('#live-notify-list').find('#notification' + slug);
                   updateElem.html(data.unread_list[i].description + 
                        "<label class='label label-primary'>" + 
                        "<span class='glyphicon glyphicon-ok' aria-hidden='true'></span></label>" + 
                        "<br><p role='separator' class='divider'></p>");
                }
            }
            fetch_api_data();
        }

        function refreshNotifications() {
            $.ajax({
                url: "{% url 'notifications:live_unread_notification_list' %}",
                type: 'get', 
                success: function(data) {
                    // console.log("success");
                    insertNotifications(data);
                    clearTimeout(timer);
                    timer = setTimeout(refreshNotifications, 5000);
                },
                failure: function(data) { 
                    setTimeout(refreshNotifications, 20000);
                }
            }); 
        }
        
        $( document ).ready(function() {
            //setTimeout(refreshNotifications, 3000);
            refreshNotifications();
            $( document ).on("click", "[id^='notification']", function() {
                // console.log("onclick " + $(this));
                removeNotification($(this));
            });
        });
    </script>
    <script type="text/javascript">
        // Script to send notifications

        // The two following functions are for CSRF protection necessary for AJAX requests in Django.
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie != '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        var csrftoken = getCookie('csrftoken');

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });

        // -----------------------------------------------------------------------------------------
        // -----------------------------------------------------------------------------------------

        // The server needs to know which listing the user is sending a notification from.
        // This will send the listing id back to the server. 
        function sendNotification() {
            var listingID = "{{ listing.pk }}";
            var URL = "{% url 'send_notification' %}"

            var data = {'listingID': listingID};
            $.post(URL, data, function(response){
                if(response === 'success'){ 
                    console.log('Yay!');
                    $('#interestedBtn').addClass("btn-success disabled").text("Sent!");
                }
                else{ console.log('Error! :('); }
            });
        }

        function getInterestedUsers() {
            var listingID = "{{ listing.pk }}";
            var URL = "{% url 'get_interested_users' %}"

            var data = {'listingID': listingID};
            $.post(URL, data, function(data){
                console.log(data);
                if (data.response === 'success') {
                    console.log("getInterestedUsers success " + data.unread_list);
                    if (data.unread_list.length === 0) {
                        $('#interested_list').html("No one interested...yet");
                        return;
                    }
                    var changes = [];
                    for (var i = 0; i < data.unread_list.length; i++) {                            
                        // Append to the list a "<a><li></li></a>"
                        changes.push("<li>" + data.unread_list[i].description + 
                            "<br><p role='separator' class='divider'></p></li>");
                    }
                    $('#interested_list').html(changes.join(""));
                }
                else {
                    console.log("fail to getInterestedUsers");
                }
            });
        }
    </script>
    {% endif %}

</body>
</html>

project/blog/templates/blog/index.html
{% extends "blog/base.html" %}
{% load staticfiles %}
{% block content %}
<div class="jumbotron" style="background: url({% static 'blog/img/cover.jpg' %}); background-size: cover;">
    <h1>Market362</h1>
    <p class="lead">Market362 is a simple platform to buy and sell products.</p>
    <p><a class="btn btn-default btn-lg" href="{% url 'listing_list' %}">Browse &raquo;</a></p>
    <br><br>
</div>
{% if user.is_authenticated %}
<h1 style="text-align: center;">Welcome, {{ user.username }}!</h1>
{% else %}
<div class="row">
    <div class="col-xs-12 col-md-4">
        <h2>Sign Up</h2>
        <p>Want to post an ad for an item you want to sell? Create a free account to start posting</p>
        <p><a class="btn btn-default" href="{% url 'register' %}">Register &raquo;</a></p>
    </div>
    <div class="col-xs-12 col-md-4">
        <h2>Existing Users</h2>
        <p>Already signed up? Sign in to create, edit or delete your listings</p>
        <p><a class="btn btn-default" href="{% url 'login' %}">Log In &raquo;</a></p>
    </div>
    <div class="col-xs-12 col-md-4">
        <h2>About Us</h2>
        <p>Learn more about the team that created Market362</p>
        <p><a class="btn btn-default" href="{% url 'about' %}">Learn More &raquo;</a></p>
    </div>
</div>
{% endif %}


{% endblock %}

project/blog/templates/blog/listing_confirm_delete.html
{% extends "blog/base.html" %}

{% block content %}

{% comment %}
	This html page contains the listings.
{% endcomment %}

<div class="page-header">
    <h1>Delete Listing</h1>
</div>
{% if user.is_authenticated %}

<div class="delete-listing">
    <form method="POST">
    	<p>Are you sure you want to delete your listing?</p>
        {% csrf_token %}
        <input type="hidden" name="next" value="{% url 'listing_list' %}" />
        <input type="submit" value="Delete" class="btn btn-default" />
        <input type="submit" name="Cancel" value="Cancel" class="btn btn-default" />
    </form>
</div>

{% else %}
<p>You must be <a href="{% url 'login' %}">logged in</a> to delete a listing.</p>
{% endif %}

{% endblock %}

project/blog/templates/blog/listing_detail.html
{% extends "blog/base.html" %}

{% block content %}

<div class="listing-detail">
	<div class="page-header">
  		<h1>{{ listing.title }}</h1>
	</div>
	{% if request.user == listing.author %}
	<div class="btn-group">
		<a href="{% url 'listing_update' listing_id=listing.pk %}" class="btn btn-default" role="button">Edit</a>
		<a href="{% url 'listing_delete' listing_id=listing.pk %}" class="btn btn-default" role="button">Delete</a>
		<div class="btn-group">
			<button onclick="getInterestedUsers();" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Who's Interested <span class="caret"></span></button>
			<ul id="interested_list" class="dropdown-menu" role="menu"></ul>
		</div>
	</div>
	{% elif request.user.is_authenticated %}
	<div class="btn-group">
		<a id="interestedBtn" onclick="sendNotification();" class="btn btn-default" role="button">I'm Interested</a>
	</div>
	{% else %}
	{% endif %}
	<h3>${{ listing.price }}</h3>
	
	<!-- This div holds the selected image (when user hovers over a thumbnail) -->
	<div class="selected">
    	<img id="selected" src="">
	</div>
	<br>
	<!-- This is a div that holds all the images in the listing as thumbnails -->
	<div class="tray">
		{% for pic in pictures %}
		<img src="{{ MEDIA_URL }}{{ pic.picture }}">
		{% endfor %}
	</div>
	<div class="page-header">
  		<h3>Item Description</h3>
	</div>
	<p>{{ listing.text|linebreaks }}</p>
	<br>
	<hr>
	<p>Seller: {{ listing.author }}</p>
	<p>Created: {{ listing.created_date }}</p>
	<p><a href="{% url 'listing_list' %}" class="btn btn-primary" role="button">Go Back</a></p>
	
</div>

{% endblock %}

project/blog/templates/blog/listing_list.html
{% extends "blog/base.html" %}

{% block content %}

{% comment %}
	This html page contains the listings.
{% endcomment %}

<div class="page-header">
    <h1>Product Listings</h1>
</div>
{% if user.is_authenticated %}
    <a href="{% url 'listing_new' %}" class="btn btn-default" role="button">+ Create Listing</a>
{% endif %}
{% if not listings %}
	<br><br>
	<h4>No listings found.</h4>
{% else %}
<div class="listing">
	<div class="row">

	<!-- Load static default thumbnail image to display if a listing has no pictures -->
	{% load static %}
	{% static 'blog/img/thumbnail-default.jpg' as default %}
	{% for listing in listings %}
	{% with listing.listingpicture_set.all.0.picture as picture %}

	  <div class="col-md-3 col-sm-6 col-xs-6 list-element">
	    <div class="thumbnail">
	      {% if picture %}
	      <img class="list-thumb" src="{{ MEDIA_URL }}{{ picture }}" alt="Thumbnail Image Here">
		  {% else %}
		  <img class="list-thumb" src="{{ default }}" alt="Thumbnail Image Here">
		  {% endif %}
	      
	      <div class="caption">
	        <h3><a href="{% url 'listing_detail' listing_id=listing.pk %}">{{ listing.title }}</a></h3>
	        <p>Price: ${{ listing.price }}</p>
	        <p>Posted: {{ listing.created_date }}</p>
            <p>Seller: {{ listing.author }}</p>
	        <p><a href="{% url 'listing_detail' listing_id=listing.pk %}" class="btn btn-primary" role="button">Details</a></p>
	      </div>
	    </div>
	  </div>
	{% endwith %}
	{% endfor %}
	</div>
</div>
{% endif %}
{% endblock %}